import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'papirsarkany.hu',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="scroll-pt-[68px] scroll-smooth sm:scroll-pt-[72px]">
      <body className={`${inter.className} `}>
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="grid flex-1 bg-sky-100">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
