name: Check version bump

on:
  pull_request:
    branches:
      - main

jobs:
  check-version-bump:
    name: Check if version number was bumped
    runs-on: ubuntu-latest
    if: github.base_ref == 'main' && github.head_ref == 'develop'
    outputs:
      should_release: ${{ steps.compare_versions.outputs.should_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest GitHub release
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(gh release list --limit 1 --json tagName -q '.[0].tagName' || echo "none")
          echo "LATEST_RELEASE: $LATEST_RELEASE" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package.json version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Print version
        run: echo "The current version is $PACKAGE_VERSION"

      - name: Compare versions
        id: compare_versions
        run: |
          if [ "v$PACKAGE_VERSION" == "$LATEST_RELEASE" ]; then
            echo "Version number has not changed! Failing the job."
            exit 1