name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check-version-bump:
    name: Check if version number was bumped
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.compare_versions.outputs.should_release }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest GitHub release
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(gh release list --limit 1 --json tagName -q '.[0].tagName' || echo "none")
          echo "latest_release=$LATEST_RELEASE" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package.json version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Print version
        run: echo "The current version is $PACKAGE_VERSION"

      - name: Compare versions
        id: compare_versions
        run: |
          if [ "$package_version" == "$latest_release" ]; then
            echo "Version number has not changed! Failing the job."
            exit 1
          fi
          echo "should_release=true" >> $GITHUB_ENV

  release:
    name: Release pushed tag
    needs: check-version-bump
    if: needs.check-version-bump.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.env.PACKAGE_VERSION }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes
