name: Lint and format

on:
  pull_request:
    branches:
      - develop

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint and format
        run: pnpm run lint-and-format
