name: Deploy Prisma migrations
on:
  push:
    paths:
      - prisma/migrations/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install

      - name: Apply all pending migrations to the database
        run: pnpx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}